### ISSUE TITLE
Crash on iOS

### ISSUE THREAD

**Issue by vietstone-ng** [llfbandit/record#173]
**Package version**
v5.0.0-beta.1

**Describe the bug**
Crash on TestFlight user

In my app, it's a long record, maybe several hours. I split the record into multiple files, 1 hour/file.
I means I stop the record and start a new one each hour.

I push the build to TestFlight for testers. One report that he turn on the record, then go to sleep. When he get up, he think the app is crash. I check the Crashes in Xcode/Organizer, then see the report as the attached image. The bug is at:
```swift
    m_audioWriter?.finishWriting(completionHandler: {
      self.m_audioWriter = nil
    })
```
Don't know why does the bug happen here? Should we capture [weak self] ?

```swift
    m_audioWriter?.finishWriting(completionHandler: { [weak self] in
      self?.m_audioWriter = nil
    })
```

**Smartphone:**
 - Device: iPhone 13 Pro
 - OS: iOS 16.2

**Additional context**

<img width="1408" alt="Screenshot 2023-06-29 at 03 11 36" src="https://github.com/llfbandit/record/assets/744353/a9dc48af-a6b1-4347-9f2d-5d5957dda0ff">
<img width="1552" alt="Screenshot 2023-06-29 at 03 11 26" src="https://github.com/llfbandit/record/assets/744353/b3366924-d07f-4c3a-9c11-6bb527baab30">

**Comment by vietstone-ng** [comment]
Thank you, let me try, will report the result after some tests (maybe 1 or 2 days)

**Comment by llfbandit** [comment]
Why are you targeting git repository?
Just the published versions on pub.dev.

**Comment by vietstone-ng** [comment]
My `flutter pub get` failed with:
`record: 5.0.0-beta.2+1`
Is that correct?

**Comment by llfbandit** [comment]
record: 5.0.0-beta.2
Darwin package will be pulled from here and should be in version 1.0.0.beta.2+1 in your `pubspec.lock` file.

**Comment by vietstone-ng** [comment]
I see, thank you. Will get back with result.

**Comment by vietstone-ng** [comment]
Hi, it seems the crash still happen.
<img width="1264" alt="Screenshot 2023-07-01 at 09 00 16" src="https://github.com/llfbandit/record/assets/744353/ca313c64-fec2-41bf-bbc4-2f899ad7bdd1">

**Comment by llfbandit** [comment]
Stop procedure has been fixed. If I understand well, you try to record to file in background state?

**Comment by vietstone-ng** [comment]
Hi,
Is interruption (by phone call, alarm) handled?

**Comment by llfbandit** [comment]
> Is that problem if the app running in background?

Yes, the package does not support it, neither the underlying systems (Android/iOS). See #69 for more details. 
I keep this issue opened to try to stop the recording when in background.
For your use case, I would recommend you to stream instead of saving audio data. And for the background issue, I would recommend to you try background fetch feature to catch audio data in allowed periods.

> Is interruption (by phone call, alarm) handled?
Yes, untested though.

**Comment by patelnirav48** [comment]
Hi @llfbandit Still crashing for iOS on record: ^5.0.0-beta.2, any update pls?

**Comment by patelnirav48** [comment]
@llfbandit Ok, Look like when i use AudioEncoder.pcm16bit, its crashing on iOS. But if i user AudioEncoder.wav working fine.

**Comment by vietstone-ng** [comment]
> For your use case, I would recommend you to stream instead of saving audio data. And for the background issue, I would recommend to you try background fetch feature to catch audio data in allowed periods.
> 
> >

Hi, could you please give me some reference about this? (stream and catch data in periods). Thank you.
